[2019-10-04 13:07:01,487] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_project_dag.Load_i94_immigration_staging_table 2019-10-04T18:06:03.624069+00:00 [queued]>
[2019-10-04 13:07:01,512] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_project_dag.Load_i94_immigration_staging_table 2019-10-04T18:06:03.624069+00:00 [queued]>
[2019-10-04 13:07:01,513] {taskinstance.py:838} INFO - 
--------------------------------------------------------------------------------
[2019-10-04 13:07:01,513] {taskinstance.py:839} INFO - Starting attempt 1 of 4
[2019-10-04 13:07:01,513] {taskinstance.py:840} INFO - 
--------------------------------------------------------------------------------
[2019-10-04 13:07:01,583] {taskinstance.py:859} INFO - Executing <Task(CopyS3ToRedshiftOperator): Load_i94_immigration_staging_table> on 2019-10-04T18:06:03.624069+00:00
[2019-10-04 13:07:01,584] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'capstone_project_dag', 'Load_i94_immigration_staging_table', '2019-10-04T18:06:03.624069+00:00', '--job_id', '626', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/project_dag.py', '--cfg_path', '/var/folders/dr/9yvjlnm11xv25k2gknf2n3z00000gn/T/tmplaqit_3_']
[2019-10-04 13:07:03,830] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table /usr/local/lib/python3.7/site-packages/airflow/configuration.py:627: DeprecationWarning: You have two airflow.cfg files: /Users/victorialemay/airflow/airflow.cfg and /Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/airflow.cfg. Airflow used to look at ~/airflow/airflow.cfg, even when AIRFLOW_HOME was set to a different value. Airflow will now only read /Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/airflow.cfg, and you should remove the other file
[2019-10-04 13:07:03,831] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table   category=DeprecationWarning,
[2019-10-04 13:07:04,336] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table [2019-10-04 13:07:04,336] {settings.py:213} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=84727
[2019-10-04 13:07:05,198] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table [2019-10-04 13:07:05,198] {__init__.py:51} INFO - Using executor LocalExecutor
[2019-10-04 13:07:06,937] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table [2019-10-04 13:07:06,936] {dagbag.py:90} INFO - Filling up the DagBag from /Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/dags/project_dag.py
[2019-10-04 13:07:07,112] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table [2019-10-04 13:07:07,111] {cli.py:516} INFO - Running <TaskInstance: capstone_project_dag.Load_i94_immigration_staging_table 2019-10-04T18:06:03.624069+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2019-10-04 13:07:07,283] {copy_s3_to_redshift.py:46} INFO - Using data file  from S3 bucket project-capstone-parquet
[2019-10-04 13:07:07,283] {copy_s3_to_redshift.py:47} INFO - Inserting into destination Redshift table i94_immigration_staging
[2019-10-04 13:07:07,388] {logging_mixin.py:95} INFO - [[34m2019-10-04 13:07:07,388[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster-1.c4i0rfzboubh.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-10-04 13:07:07,963] {logging_mixin.py:95} INFO - [[34m2019-10-04 13:07:07,963[0m] {[34mdbapi_hook.py:[0m171} INFO[0m - TRUNCATE TABLE i94_immigration_staging[0m
[2019-10-04 13:07:08,365] {copy_s3_to_redshift.py:56} INFO - Copying data from S3 to Redshift
[2019-10-04 13:07:08,383] {logging_mixin.py:95} INFO - [[34m2019-10-04 13:07:08,383[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster-1.c4i0rfzboubh.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-10-04 13:07:08,955] {logging_mixin.py:95} INFO - [[34m2019-10-04 13:07:08,955[0m] {[34mdbapi_hook.py:[0m171} INFO[0m - 
        COPY i94_immigration_staging
        FROM 's3://project-capstone-parquet/'
        IAM_ROLE 'arn:aws:iam::191711490296:role/myRedshiftRole'
        FORMAT AS PARQUET
    [0m
[2019-10-04 13:07:23,810] {taskinstance.py:1051} ERROR - S3 Query Exception (Fetch)
DETAIL:  
  -----------------------------------------------
  error:  S3 Query Exception (Fetch)
  code:      15001
  context:   Task failed due to an internal error. File 'https://s3.us-west-2.amazonaws.com/project-capstone-parquet/part-00000-b9542815-7a8d-45fc-9c67-c9c5007ad0d4-c000.snappy.parquet  has an incompatible Parquet schema for column 's3://project-capstone-parquet/.cicid
  query:     1096
  location:  dory_util.cpp:931
  process:   query0_114_1096 [pid=21773]
  -----------------------------------------------

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/plugins/operators/copy_s3_to_redshift.py", line 74, in execute
    redshift.run(formatted_sql)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 172, in run
    cur.execute(s)
psycopg2.errors.InternalError_: S3 Query Exception (Fetch)
DETAIL:  
  -----------------------------------------------
  error:  S3 Query Exception (Fetch)
  code:      15001
  context:   Task failed due to an internal error. File 'https://s3.us-west-2.amazonaws.com/project-capstone-parquet/part-00000-b9542815-7a8d-45fc-9c67-c9c5007ad0d4-c000.snappy.parquet  has an incompatible Parquet schema for column 's3://project-capstone-parquet/.cicid
  query:     1096
  location:  dory_util.cpp:931
  process:   query0_114_1096 [pid=21773]
  -----------------------------------------------


[2019-10-04 13:07:23,815] {taskinstance.py:1074} INFO - Marking task as UP_FOR_RETRY
[2019-10-04 13:07:23,839] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table Traceback (most recent call last):
[2019-10-04 13:07:23,839] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table   File "/usr/local/bin/airflow", line 32, in <module>
[2019-10-04 13:07:23,839] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table     args.func(args)
[2019-10-04 13:07:23,839] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-10-04 13:07:23,839] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table     return f(*args, **kwargs)
[2019-10-04 13:07:23,840] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2019-10-04 13:07:23,840] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table     _run(args, dag, ti)
[2019-10-04 13:07:23,840] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2019-10-04 13:07:23,840] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table     pool=args.pool,
[2019-10-04 13:07:23,840] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-10-04 13:07:23,840] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table     return func(*args, **kwargs)
[2019-10-04 13:07:23,840] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table   File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
[2019-10-04 13:07:23,840] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table     result = task_copy.execute(context=context)
[2019-10-04 13:07:23,840] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table   File "/Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/plugins/operators/copy_s3_to_redshift.py", line 74, in execute
[2019-10-04 13:07:23,840] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table     redshift.run(formatted_sql)
[2019-10-04 13:07:23,840] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 172, in run
[2019-10-04 13:07:23,840] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table     cur.execute(s)
[2019-10-04 13:07:23,840] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table psycopg2.errors.InternalError_: S3 Query Exception (Fetch)
[2019-10-04 13:07:23,840] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table DETAIL:  
[2019-10-04 13:07:23,840] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table   -----------------------------------------------
[2019-10-04 13:07:23,841] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table   error:  S3 Query Exception (Fetch)
[2019-10-04 13:07:23,841] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table   code:      15001
[2019-10-04 13:07:23,841] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table   context:   Task failed due to an internal error. File 'https://s3.us-west-2.amazonaws.com/project-capstone-parquet/part-00000-b9542815-7a8d-45fc-9c67-c9c5007ad0d4-c000.snappy.parquet  has an incompatible Parquet schema for column 's3://project-capstone-parquet/.cicid
[2019-10-04 13:07:23,841] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table   query:     1096
[2019-10-04 13:07:23,841] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table   location:  dory_util.cpp:931
[2019-10-04 13:07:23,841] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table   process:   query0_114_1096 [pid=21773]
[2019-10-04 13:07:23,841] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table   -----------------------------------------------
[2019-10-04 13:07:23,841] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table 
[2019-10-04 13:07:23,841] {base_task_runner.py:115} INFO - Job 626: Subtask Load_i94_immigration_staging_table 
[2019-10-04 13:07:26,391] {logging_mixin.py:95} INFO - [[34m2019-10-04 13:07:26,390[0m] {[34mlocal_task_job.py:[0m105} INFO[0m - Task exited with return code 1[0m
