[2019-10-04 19:56:53,887] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_project_dag.Run_final_tables_quality_checks 2019-10-05T00:36:59.504753+00:00 [queued]>
[2019-10-04 19:56:53,897] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_project_dag.Run_final_tables_quality_checks 2019-10-05T00:36:59.504753+00:00 [queued]>
[2019-10-04 19:56:53,897] {taskinstance.py:838} INFO - 
--------------------------------------------------------------------------------
[2019-10-04 19:56:53,897] {taskinstance.py:839} INFO - Starting attempt 4 of 4
[2019-10-04 19:56:53,897] {taskinstance.py:840} INFO - 
--------------------------------------------------------------------------------
[2019-10-04 19:56:53,919] {taskinstance.py:859} INFO - Executing <Task(DataQualityCheckOperator): Run_final_tables_quality_checks> on 2019-10-05T00:36:59.504753+00:00
[2019-10-04 19:56:53,919] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'capstone_project_dag', 'Run_final_tables_quality_checks', '2019-10-05T00:36:59.504753+00:00', '--job_id', '1017', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/project_dag.py', '--cfg_path', '/var/folders/dr/9yvjlnm11xv25k2gknf2n3z00000gn/T/tmpd8aa841o']
[2019-10-04 19:56:54,447] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks /usr/local/lib/python3.7/site-packages/airflow/configuration.py:627: DeprecationWarning: You have two airflow.cfg files: /Users/victorialemay/airflow/airflow.cfg and /Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/airflow.cfg. Airflow used to look at ~/airflow/airflow.cfg, even when AIRFLOW_HOME was set to a different value. Airflow will now only read /Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/airflow.cfg, and you should remove the other file
[2019-10-04 19:56:54,447] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks   category=DeprecationWarning,
[2019-10-04 19:56:54,545] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks [2019-10-04 19:56:54,545] {settings.py:213} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=1651
[2019-10-04 19:56:54,768] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks [2019-10-04 19:56:54,767] {__init__.py:51} INFO - Using executor LocalExecutor
[2019-10-04 19:56:55,189] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks [2019-10-04 19:56:55,188] {dagbag.py:90} INFO - Filling up the DagBag from /Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/dags/project_dag.py
[2019-10-04 19:56:55,239] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks [2019-10-04 19:56:55,239] {cli.py:516} INFO - Running <TaskInstance: capstone_project_dag.Run_final_tables_quality_checks 2019-10-05T00:36:59.504753+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2019-10-04 19:56:55,275] {data_quality_check.py:42} INFO - Checking data in port_id column of i94_immigration table
[2019-10-04 19:56:55,289] {logging_mixin.py:95} INFO - [[34m2019-10-04 19:56:55,289[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster-1.c4i0rfzboubh.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-10-04 19:56:56,104] {data_quality_check.py:51} INFO - Found records in i94_immigration
[2019-10-04 19:56:56,104] {data_quality_check.py:42} INFO - Checking data in i94_port_code column of port_codes table
[2019-10-04 19:56:56,118] {logging_mixin.py:95} INFO - [[34m2019-10-04 19:56:56,118[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster-1.c4i0rfzboubh.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-10-04 19:56:56,840] {data_quality_check.py:51} INFO - Found records in port_codes
[2019-10-04 19:56:56,840] {data_quality_check.py:42} INFO - Checking data in date column of land_temperatures table
[2019-10-04 19:56:56,857] {logging_mixin.py:95} INFO - [[34m2019-10-04 19:56:56,857[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster-1.c4i0rfzboubh.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-10-04 19:56:57,590] {data_quality_check.py:51} INFO - Found records in land_temperatures
[2019-10-04 19:56:57,590] {data_quality_check.py:42} INFO - Checking data in port_code_id column of us_city_demographics table
[2019-10-04 19:56:57,604] {logging_mixin.py:95} INFO - [[34m2019-10-04 19:56:57,604[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster-1.c4i0rfzboubh.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-10-04 19:56:58,330] {data_quality_check.py:51} INFO - Found records in us_city_demographics
[2019-10-04 19:56:58,331] {data_quality_check.py:30} INFO - Checking data in port_id column of i94_immigration table
[2019-10-04 19:56:58,344] {logging_mixin.py:95} INFO - [[34m2019-10-04 19:56:58,344[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster-1.c4i0rfzboubh.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-10-04 19:56:59,065] {data_quality_check.py:35} INFO - Found [(0,)] NULL records
[2019-10-04 19:56:59,065] {taskinstance.py:1051} ERROR - NULL records were found for the port_id column
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/plugins/operators/data_quality_check.py", line 24, in execute
    getattr(self, check_function)(redshift_hook)
  File "/Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/plugins/operators/data_quality_check.py", line 36, in has_nulls
    raise ValueError("NULL records were found for the {} column".format(column))
ValueError: NULL records were found for the port_id column
[2019-10-04 19:56:59,069] {taskinstance.py:1080} INFO - All retries failed; marking task as FAILED
[2019-10-04 19:56:59,093] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks Traceback (most recent call last):
[2019-10-04 19:56:59,094] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks   File "/usr/local/bin/airflow", line 32, in <module>
[2019-10-04 19:56:59,094] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks     args.func(args)
[2019-10-04 19:56:59,094] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks   File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-10-04 19:56:59,094] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks     return f(*args, **kwargs)
[2019-10-04 19:56:59,094] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2019-10-04 19:56:59,094] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks     _run(args, dag, ti)
[2019-10-04 19:56:59,094] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2019-10-04 19:56:59,094] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks     pool=args.pool,
[2019-10-04 19:56:59,094] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-10-04 19:56:59,094] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks     return func(*args, **kwargs)
[2019-10-04 19:56:59,094] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks   File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
[2019-10-04 19:56:59,095] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks     result = task_copy.execute(context=context)
[2019-10-04 19:56:59,095] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks   File "/Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/plugins/operators/data_quality_check.py", line 24, in execute
[2019-10-04 19:56:59,095] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks     getattr(self, check_function)(redshift_hook)
[2019-10-04 19:56:59,095] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks   File "/Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/plugins/operators/data_quality_check.py", line 36, in has_nulls
[2019-10-04 19:56:59,095] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks     raise ValueError("NULL records were found for the {} column".format(column))
[2019-10-04 19:56:59,095] {base_task_runner.py:115} INFO - Job 1017: Subtask Run_final_tables_quality_checks ValueError: NULL records were found for the port_id column
[2019-10-04 19:57:03,887] {logging_mixin.py:95} INFO - [[34m2019-10-04 19:57:03,886[0m] {[34mlocal_task_job.py:[0m105} INFO[0m - Task exited with return code 1[0m
